export function operatorPage(): Response {
  return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex,nofollow"><title>Miller intake operations</title>
<style>body{font:18px system-ui;max-width:760px;margin:40px auto;padding:20px;background:#f5f3ec;color:#1b2420}label{display:block;margin:16px 0}input,select,button{font:inherit;padding:10px;max-width:100%;box-sizing:border-box}input{width:100%}button{cursor:pointer;margin:5px}pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:16px;background:white}fieldset{margin:24px 0}a{color:inherit}</style>
<h1>Intake operations</h1><p><a href="/operator/google/connect">Connect Erik’s Google booking calendar</a></p><p>With the Google connection configured, bookings, reschedules, and cancellations synchronize automatically every five minutes. Use this page when delivery needs attention.</p><p>Check delivery before retrying. For an uncertain write, locate the exact reference in JobTread and verify it before recording the outcome.</p>
<button id="readiness">Check connection setup</button><button id="sync">Run calendar sync</button>
<form id="lookup"><label>Inquiry reference<input id="receipt" required pattern="[a-fA-F0-9-]{36}"></label><button>Check delivery</button><button type="button" id="retry">Retry delivery</button></form>
<pre id="status" role="status" aria-live="polite">Enter the reference from the inquiry confirmation.</pre>
<fieldset><legend>Reconcile an uncertain write</legend><label>Delivery step<input id="step" placeholder="account, location, contact, job, photo_0_upload, photo_0_file"></label><label>Verified outcome<select id="outcome"><option value="present">Record exists and matches this inquiry</option><option value="absent">Confirmed no record exists</option></select></label><label>Existing JobTread record ID (when present)<input id="record"></label><button id="reconcile">Record outcome and continue</button></fieldset>
<fieldset><legend>Associate a consultation</legend><p>Use the project reference supplied with the Google booking. Read the confirmed appointment from Erik’s calendar. Times below are in America/Denver.</p><label>Google event ID<input id="event"></label><label>Date<input id="date" type="date"></label><label>Start time<input id="start" type="time"></label><label>End time<input id="end" type="time"></label><button id="booking">Record consultation in JobTread</button></fieldset>
<fieldset><legend>Reconcile an uncertain consultation</legend><p>Use the event ID above and the verified outcome / record ID above. Check the JobTread task’s job and dates before confirming.</p><button id="booking-reconcile">Reconcile consultation</button></fieldset>
<script>
const get=id=>document.getElementById(id), status=get('status');
async function action(suffix,body){const receipt=get('receipt').value.trim();if(!/^[0-9a-f-]{36}$/i.test(receipt)){status.textContent='Enter a valid inquiry reference.';return;}status.textContent='Working…';const buttons=document.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{const response=await fetch('/operator/intake/'+encodeURIComponent(receipt)+suffix,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();status.textContent=JSON.stringify(result,null,2);}catch{status.textContent='Operation could not be confirmed. Check delivery before trying again.';}finally{buttons.forEach(b=>b.disabled=false);}}
get('lookup').onsubmit=e=>{e.preventDefault();action('');};get('retry').onclick=()=>action('/retry',{});get('reconcile').onclick=()=>action('/reconcile',{step:get('step').value.trim(),outcome:get('outcome').value,...(get('outcome').value==='present'?{recordId:get('record').value.trim()}:{})});get('booking').onclick=()=>action('/booking',{eventId:get('event').value.trim(),date:get('date').value,start:get('start').value,end:get('end').value});get('booking-reconcile').onclick=()=>action('/booking-reconcile',{eventId:get('event').value.trim(),outcome:get('outcome').value,...(get('outcome').value==='present'?{recordId:get('record').value.trim()}:{})});
async function setup(path,method='GET'){try{const response=await fetch(path,{method});status.textContent=JSON.stringify(await response.json(),null,2);}catch{status.textContent='The setup check could not complete.';}}get('readiness').onclick=()=>setup('/operator/readiness');get('sync').onclick=()=>setup('/operator/calendar/sync','POST');
</script></html>`, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer' } });
}
