export function operatorPage(): Response {
  return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex,nofollow"><title>Miller intake operations</title>
<style>body{font:18px system-ui;max-width:760px;margin:40px auto;padding:20px;background:#f5f3ec;color:#1b2420}label{display:block;margin:16px 0}input,select,button{font:inherit;padding:10px;max-width:100%;box-sizing:border-box}input{width:100%}input[type=checkbox]{width:auto}button{cursor:pointer;margin:5px}pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:16px;background:white}fieldset{margin:24px 0}a{color:inherit}</style>
<h1>Intake operations</h1><p><a href="/operator/google/connect">Connect Erik’s Google booking calendar</a></p><p>With the Google connection configured, bookings, reschedules, and cancellations synchronize automatically every five minutes. Use this page when delivery needs attention.</p><p>Check delivery before retrying. For an uncertain write, locate the exact reference in JobTread and verify it before recording the outcome.</p>
<fieldset><legend>Lead conversion setup · email only</legend><p>SMS is deferred. Configure real budget ranges, approved guide content, review requests, and up to three follow-ups. Changes require Erik’s approval before activation. No message is sent from this setup screen.</p><button id="conversion-load">Load settings</button><button id="conversion-status">Check follow-up delivery</button>
<form id="conversion-form"><h2>Budget ranges</h2><p>Leave a project blank until Erik confirms its range and scope. These are planning ranges, never quotes.</p><div id="bands"></div>
<h2>Cost guide</h2><label><input type="checkbox" id="guide-enabled"> Offer the approved guide</label><label>Guide title<input id="guide-title" maxlength="160"></label><label>Approved guide text<textarea id="guide-text" rows="12" maxlength="40000" style="width:100%;font:inherit"></textarea></label>
<h2>Email sender</h2><label>Verified sending address<input id="sender" type="email"></label><label>Reply-to address<input id="reply-to" type="email"></label><label>Business mailing address for message footer<input id="postal-address"></label>
<h2>Review requests</h2><label><input type="checkbox" id="reviews-enabled"> Enable email review requests after confirmed job closure</label><label>Days after completion<input id="review-days" type="number" min="0" max="30"></label><p>Up to three confirmed direct review links. Optional feedback, with no incentives or sentiment filtering.</p><div id="review-links"></div><label>Request subject<input id="review-subject"></label><label>Request copy<textarea id="review-ask" rows="4" style="width:100%;font:inherit"></textarea></label><label>Thank-you copy<textarea id="review-thanks" rows="3" style="width:100%;font:inherit"></textarea></label>
<h2>Bounded follow-up</h2><label><input type="checkbox" id="nurture-enabled"> Enable follow-ups for homeowners who opt in by email</label><p>At most three touches within fourteen days. Booking, unsubscribe, or an operator stop ends the sequence. Calendar sync must be enabled.</p><div id="touches"></div><button type="submit">Save draft and require approval</button><button type="button" id="conversion-approve">Erik: approve this exact draft</button></form>
<label>Stop follow-ups for an inquiry<input id="conversion-stop-receipt" placeholder="Inquiry reference"></label><button id="conversion-stop">Stop follow-ups</button><pre id="conversion-result" role="status" aria-live="polite">Load settings to begin. Sending is disabled until setup and approval are complete.</pre></fieldset>
<fieldset><legend>Completed jobs and message recovery</legend><p>For a completed JobTread job, supply the customer contact belonging to that job’s account. Job closure, organization, and email are verified before scheduling a review request. This can also receive a JobTread Workflow event once connected.</p><label>JobTread job ID<input id="conversion-job"></label><label>JobTread customer contact ID<input id="conversion-contact"></label><button id="conversion-completion">Verify completion and schedule review request</button><p>For an uncertain email send, check the provider log first. Mark absent only after confirming that no email was accepted.</p><label>Message ID from delivery status<input id="conversion-message"></label><label>Verified send outcome<select id="conversion-outcome"><option value="sent">Email accepted by provider</option><option value="absent">Confirmed no email accepted</option></select></label><label>Verified provider message ID<input id="conversion-provider"></label><button id="conversion-reconcile">Record verified outcome</button></fieldset>
<button id="readiness">Check connection setup</button><button id="sync">Run calendar sync</button>
<form id="lookup"><label>Inquiry reference<input id="receipt" required pattern="[a-fA-F0-9-]{36}"></label><button>Check delivery</button><button type="button" id="retry">Retry delivery</button></form>
<pre id="status" role="status" aria-live="polite">Enter the reference from the inquiry confirmation.</pre>
<fieldset><legend>Reconcile an uncertain write</legend><label>Delivery step<input id="step" placeholder="account, location, contact, job, photo_0_upload, photo_0_file"></label><label>Verified outcome<select id="outcome"><option value="present">Record exists and matches this inquiry</option><option value="absent">Confirmed no record exists</option></select></label><label>Existing JobTread record ID (when present)<input id="record"></label><button id="reconcile">Record outcome and continue</button></fieldset>
<fieldset><legend>Associate a consultation</legend><p>Use the project reference supplied with the Google booking. Read the confirmed appointment from Erik’s calendar. Times below are in America/Denver.</p><label>Google event ID<input id="event"></label><label>Date<input id="date" type="date"></label><label>Start time<input id="start" type="time"></label><label>End time<input id="end" type="time"></label><button id="booking">Record consultation in JobTread</button></fieldset>
<fieldset><legend>Reconcile an uncertain consultation</legend><p>Use the event ID above and the verified outcome / record ID above. Check the JobTread task’s job and dates before confirming.</p><button id="booking-reconcile">Reconcile consultation</button></fieldset>
<script>
const get=id=>document.getElementById(id), status=get('status');
let revision=null;const conversionResult=get('conversion-result');
const types=['Kitchen','Bathroom','Whole home','Addition','ADU or mother-in-law space','Home repair','Another project'];
function input(parent,id,label,type='text'){const wrap=document.createElement('label');wrap.textContent=label;const field=document.createElement(type==='textarea'?'textarea':'input');field.id=id;if(type!=='textarea')field.type=type;else{field.rows=3;field.style.width='100%';field.style.font='inherit';}wrap.append(field);parent.append(wrap);return field;}
types.forEach((name,i)=>{const group=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=name;group.append(legend);input(group,'band-min-'+i,'Minimum planning range','number');input(group,'band-max-'+i,'Maximum planning range','number');input(group,'band-scope-'+i,'Scope covered');get('bands').append(group);});
for(let i=0;i<3;i++){input(get('review-links'),'link-label-'+i,'Platform '+(i+1));input(get('review-links'),'link-url-'+i,'Direct review link '+(i+1),'url');input(get('touches'),'touch-day-'+i,'Touch '+(i+1)+' — day after inquiry','number');input(get('touches'),'touch-subject-'+i,'Subject');input(get('touches'),'touch-text-'+i,'Message','textarea');}
async function conversionRequest(path,method='GET',body){const r=await fetch('/operator/conversion/'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const value=await r.json();if(!r.ok)throw new Error(value.error||'Could not confirm the operation.');return value;}
function fillConversion(result){revision=result.revision;const c=result.draft;types.forEach((name,i)=>{const b=c.budgetBands.find(b=>b.projectType===name);get('band-min-'+i).value=b?.min??'';get('band-max-'+i).value=b?.max??'';get('band-scope-'+i).value=b?.scope??'';});get('guide-enabled').checked=c.guide.enabled;get('guide-title').value=c.guide.title;get('guide-text').value=c.guide.text;get('sender').value=c.sender;get('reply-to').value=c.replyTo;get('postal-address').value=c.postalAddress;get('reviews-enabled').checked=c.reviews.enabled;get('review-days').value=c.reviews.delayDays;get('review-subject').value=c.reviews.subject;get('review-ask').value=c.reviews.ask;get('review-thanks').value=c.reviews.thanks;get('nurture-enabled').checked=c.nurture.enabled;for(let i=0;i<3;i++){get('link-label-'+i).value=c.reviews.links[i]?.label??'';get('link-url-'+i).value=c.reviews.links[i]?.url??'';get('touch-day-'+i).value=c.nurture.touches[i]?.day??'';get('touch-subject-'+i).value=c.nurture.touches[i]?.subject??'';get('touch-text-'+i).value=c.nurture.touches[i]?.text??'';}conversionResult.textContent='Loaded. '+(result.approvedBy?'Approved by '+result.approvedBy+'. ':'Approval pending. ')+(result.enabled?'Activation switch on. ':'Activation switch off. ')+(result.emailBound?'Email sender connected.':'Email sender not connected.');}
get('conversion-load').onclick=async()=>{try{fillConversion(await conversionRequest('config'));}catch(e){conversionResult.textContent=e.message;}};
get('conversion-form').oninput=()=>{revision=null;conversionResult.textContent='Unsaved changes. Save the draft before approving it.';};
get('conversion-status').onclick=async()=>{try{conversionResult.textContent=JSON.stringify(await conversionRequest('status'),null,2);}catch(e){conversionResult.textContent=e.message;}};
get('conversion-form').onsubmit=async e=>{e.preventDefault();const c={budgetBands:types.flatMap((projectType,i)=>get('band-min-'+i).value||get('band-max-'+i).value?[{projectType,min:Number(get('band-min-'+i).value),max:Number(get('band-max-'+i).value),scope:get('band-scope-'+i).value}]:[]),guide:{enabled:get('guide-enabled').checked,title:get('guide-title').value,text:get('guide-text').value},sender:get('sender').value,replyTo:get('reply-to').value,postalAddress:get('postal-address').value,reviews:{enabled:get('reviews-enabled').checked,delayDays:Number(get('review-days').value),links:[0,1,2].flatMap(i=>get('link-url-'+i).value?[{label:get('link-label-'+i).value,url:get('link-url-'+i).value}]:[]),subject:get('review-subject').value,ask:get('review-ask').value,thanks:get('review-thanks').value},nurture:{enabled:get('nurture-enabled').checked,touches:[0,1,2].flatMap(i=>get('touch-day-'+i).value?[{day:Number(get('touch-day-'+i).value),subject:get('touch-subject-'+i).value,text:get('touch-text-'+i).value}]:[])}};try{const result=await conversionRequest('config','PUT',c);revision=result.revision;conversionResult.textContent='Draft saved. Erik must approve this exact version. Existing pending messages were cancelled.';}catch(e){conversionResult.textContent=e.message;}};
get('conversion-approve').onclick=async()=>{try{await conversionRequest('approve','POST',{revision});conversionResult.textContent='Approval saved. Activation and sender setup are separate; this did not send messages.';}catch(e){conversionResult.textContent=e.message;}};
get('conversion-stop').onclick=async()=>{try{await conversionRequest('stop','POST',{receiptId:get('conversion-stop-receipt').value.trim()});conversionResult.textContent='Follow-ups stopped.';}catch(e){conversionResult.textContent=e.message;}};
get('conversion-completion').onclick=async()=>{try{conversionResult.textContent=JSON.stringify(await conversionRequest('completed-job','POST',{jobId:get('conversion-job').value.trim(),contactId:get('conversion-contact').value.trim()}),null,2);}catch(e){conversionResult.textContent=e.message;}};
get('conversion-reconcile').onclick=async()=>{try{conversionResult.textContent=JSON.stringify(await conversionRequest('reconcile','POST',{id:get('conversion-message').value.trim(),outcome:get('conversion-outcome').value,...(get('conversion-outcome').value==='sent'?{providerId:get('conversion-provider').value.trim()}:{})}),null,2);}catch(e){conversionResult.textContent=e.message;}};
async function action(suffix,body){const receipt=get('receipt').value.trim();if(!/^[0-9a-f-]{36}$/i.test(receipt)){status.textContent='Enter a valid inquiry reference.';return;}status.textContent='Working…';const buttons=document.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{const response=await fetch('/operator/intake/'+encodeURIComponent(receipt)+suffix,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();status.textContent=JSON.stringify(result,null,2);}catch{status.textContent='Operation could not be confirmed. Check delivery before trying again.';}finally{buttons.forEach(b=>b.disabled=false);}}
get('lookup').onsubmit=e=>{e.preventDefault();action('');};get('retry').onclick=()=>action('/retry',{});get('reconcile').onclick=()=>action('/reconcile',{step:get('step').value.trim(),outcome:get('outcome').value,...(get('outcome').value==='present'?{recordId:get('record').value.trim()}:{})});get('booking').onclick=()=>action('/booking',{eventId:get('event').value.trim(),date:get('date').value,start:get('start').value,end:get('end').value});get('booking-reconcile').onclick=()=>action('/booking-reconcile',{eventId:get('event').value.trim(),outcome:get('outcome').value,...(get('outcome').value==='present'?{recordId:get('record').value.trim()}:{})});
async function setup(path,method='GET'){try{const response=await fetch(path,{method});status.textContent=JSON.stringify(await response.json(),null,2);}catch{status.textContent='The setup check could not complete.';}}get('readiness').onclick=()=>setup('/operator/readiness');get('sync').onclick=()=>setup('/operator/calendar/sync','POST');
</script></html>`, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer' } });
}
